osx_image: xcode7.3
sudo: required
dist: trusty
language: c
matrix:
  fast_finish: true
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
cache:
  yarn: true
  directories:
  - $HOME/.yarn-cache
  - $HOME/.electron
  - $HOME/.cache
addons:
  apt:
    packages:
    - g++-4.8
    - libgnome-keyring-dev
    - icnsutils
    - graphicsmagick
    - xz-utils
    - xorriso
env:
  global:
  - 'NODE_VERSION=6'
# branches:
#   only:
#   - "/^v[0-9]/"
before_install:
- export CXX="g++-4.8"
- nvm install $NODE_VERSION
- nvm use --delete-prefix $NODE_VERSION
- npm install --global yarn
install:
- yarn install
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sh -c "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  fi
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start &
- sleep 3
script:
- yarn run test
- yarn run build
- yarn run test-e2e
after_success:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    yarn run package-linux
	fi
- |
	if [ "$TRAVIS_OS_NAME" == "osx" ]; then
		security delete-keychain mac-build.keychain
	fi
- |
	if [ "$TRAVIS_OS_NAME" == "osx" ]; then
		yarn run package-mac
	fi
- |
	if [ "$TRAVIS_OS_NAME" == "osx" ]; then
		security delete-keychain mac-build.keychain
	fi
deploy:
- provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: sgFLuz8Or6bk4fD1y0Lr2tkWE4E20YXrTBqDYrHvcpWFiUmgE4q5UckWYHk5v+EYO6Tf0xrGwU863P9mv7wJiaCuK6p0g7JWkvGidnve1stt9X532Xcudmw+VM/kmGxGw4lkmLTgmAU73P+EjoyGMr8hpFgPw3FBF2jy/JPDHXlBimOBxJvHSkzdByj7jPqSBW7nnYIL81CWkq2wKJUXcxU6FPulpelCosoJ7WfzqabqYYZfidQhSl9hlw52F/uEztkv5XrXmUt28swXOhUSQwhmyivtQCuRAe97eok6dHA7vgUzvx7+1erEcTAhX9qysCBPJ4Y5y9+jUVhXrASP6ng60fFPTXZTOdOQpq4XLgRdE0LCQQ5JmVTzkhKLU6SFPfLAFZN7nlBwfH4R8SAXJ9cNLk1ag3YtLk0x6SZFli2u7xi4DCsX/cD/gkpDMDO3jEmyK1OZmNb5wNyXp8c8if9PxxCs2hMXtmptJgJL8i5ZaeTAkUfI/NCV69QWd50NkqhOhwPLlbeJthR4CshODIabRy+D8XuOwDwnJATZSKya8yMBJ2ZCGA0zwxV6TLUBkmlVxcGSLXvhrPs2ODlgfXY+kzL2oZE0An7kk7IZumO5anvoBuvDknnq8NNrQKcvFIwUVTQyf1+NJZsCmTVin5vMuTAWiKZI6TME0Zo34ng=
  on:
    tags: true
