branches:
  only:
  - "/^v[0-9]/"
matrix:
  include:
    - os: osx
      osx_image: xcode7.2
      dist: trusty
      language: node_js
      node_js: '6'
      cache:
        yarn: true
        directories:
        - app/node_modules
        - node_modules
        - $HOME/.electron
        - $HOME/.cache
      env:
        build: 'osx'
        global:
          - CSC_LINK=https://s3-us-west-2.amazonaws.com/meshblu-connector/certs/MeshbluConnectorMacCert.p12
      before_install:
      - npm install --global yarn
      - |
        if [ -n "$TRAVIS_TAG" ]; then
          pushd ./app
            npm version $TRAVIS_TAG
          popd
        fi
      install:
      - yarn install || exit 1
      script:
      - yarn run test || exit 1
      - yarn run build || exit 1
      - yarn run test-e2e || exit 1
      after_success:
      - yarn run package-mac -- --publish onTag || exit 1
    - os: linux
      dist: trusty
      language: node_js
      node_js: '6'
      sudo: required
      env:
        build: 'win'
        global:
          - CSC_LINK=https://s3-us-west-2.amazonaws.com/meshblu-connector/certs/CodeSigningCert.p12
      services:
      - docker
      before_install:
      - docker pull electronuserland/electron-builder:wine
      - |
        if [ -n "$TRAVIS_TAG" ]; then
          pushd ./app
            npm version $TRAVIS_TAG
          popd
        fi
      install:
      - docker build --file ./deploy/windows/Dockerfile --tag travis/electron-meshblu-connector-installer .
      script:
      - |
        docker run --rm \
          --volume "$HOME/.electron:/root/.electron" \
          --volume "$PWD/release:/project/release" \
          --env "CSC_LINK=$CSC_LINK" \
          --env "CSC_KEY_PASSWORD=$CSC_KEY_PASSWORD" \
          --env "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG" \
          --env "GH_TOKEN=$GH_TOKEN" \
          --env "CI=true" \
          travis/electron-meshblu-connector-installer 2>&1 | grep -v 'pass'
    - os: linux
      language: node_js
      node_js: '6'
      dist: trusty
      sudo: false
      cache:
        yarn: true
        directories:
        - app/node_modules
        - node_modules
        - $HOME/.electron
        - $HOME/.cache
      env:
        build: 'linux'
        global:
          - CSC_LINK=https://s3-us-west-2.amazonaws.com/meshblu-connector/certs/OtherCodeSigningCert.p12
      addons:
        apt:
          packages:
          - g++-multilib
          - xz-utils
      before_install:
      - npm install --global yarn
      - |
        if [ -n "$TRAVIS_TAG" ]; then
          pushd ./app
            npm version $TRAVIS_TAG
          popd
        fi
      install:
      - yarn install
      - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
      before_script:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start &
      - sleep 3
      script:
      - yarn run test
      - yarn run build
      - yarn run test-e2e
      after_success:
      - yarn run package-linux-all -- --publish onTag
      deploy:
      - provider: npm
        email: serveradmin@octoblu.com
        api_key:
          secure: sgFLuz8Or6bk4fD1y0Lr2tkWE4E20YXrTBqDYrHvcpWFiUmgE4q5UckWYHk5v+EYO6Tf0xrGwU863P9mv7wJiaCuK6p0g7JWkvGidnve1stt9X532Xcudmw+VM/kmGxGw4lkmLTgmAU73P+EjoyGMr8hpFgPw3FBF2jy/JPDHXlBimOBxJvHSkzdByj7jPqSBW7nnYIL81CWkq2wKJUXcxU6FPulpelCosoJ7WfzqabqYYZfidQhSl9hlw52F/uEztkv5XrXmUt28swXOhUSQwhmyivtQCuRAe97eok6dHA7vgUzvx7+1erEcTAhX9qysCBPJ4Y5y9+jUVhXrASP6ng60fFPTXZTOdOQpq4XLgRdE0LCQQ5JmVTzkhKLU6SFPfLAFZN7nlBwfH4R8SAXJ9cNLk1ag3YtLk0x6SZFli2u7xi4DCsX/cD/gkpDMDO3jEmyK1OZmNb5wNyXp8c8if9PxxCs2hMXtmptJgJL8i5ZaeTAkUfI/NCV69QWd50NkqhOhwPLlbeJthR4CshODIabRy+D8XuOwDwnJATZSKya8yMBJ2ZCGA0zwxV6TLUBkmlVxcGSLXvhrPs2ODlgfXY+kzL2oZE0An7kk7IZumO5anvoBuvDknnq8NNrQKcvFIwUVTQyf1+NJZsCmTVin5vMuTAWiKZI6TME0Zo34ng=
        on:
          tags: true
