matrix:
  include:
    - os: osx
      osx_image: xcode8
      dist: trusty
      language: node_js
      node_js: '6'
      cache:
        yarn: true
        directories:
        - $HOME/.electron
        - $HOME/.cache
      env:
        global:
          - KEY_CHAIN=mac-build.keychain
      before_install:
      - npm install --global yarn
      install:
      - yarn install || exit 1
      script:
      - yarn run test || exit 1
      - yarn run build || exit 1
      - yarn run test-e2e || exit 1
      after_success:
      - security create-keychain -p travis "$KEY_CHAIN" || exit 1
      - security import "$PWD/deploy/certs/apple.cer" -k "$KEY_CHAIN" -T /usr/bin/codesign || exit 1
      - security import "$PWD/deploy/certs/app.p12" -k "$KEY_CHAIN" -P "$CSC_KEY_PASSWORD" -T /usr/bin/codesign -T /usr/bin/productbuild || exit 1
      - security default-keychain -s "$KEY_CHAIN" || exit 1
      - security unlock-keychain -p travis "$KEY_CHAIN" || exit 1
      - security set-keychain-settings -t 3600 -u || exit 1
      - yarn run package-mac -- --publish onTagOrDraft --draft || exit 1
    - os: linux
      dist: trusty
      language: node_js
      node_js: '6'
      sudo: required
      services:
      - docker
      before_install:
      - docker pull electronuserland/electron-builder:wine
      install:
      - docker build --tag travis/electron-meshblu-connector-installer .
      script:
      - mkdir -p release
      - ls -la release
      - |
        docker run --rm \
          --volume "$HOME/.electron:/root/.electron" \
          --volume "$PWD/release:/project/release" \
          travis/electron-meshblu-connector-installer
      after_success:
      - ls -la release
      - sudo chown -R travis:travis ./release
      - sudo chmod -R 755 ./release
      - ls -la release
      deploy:
      - provider: releases
        api_key:
          secure: "SZ41iBSzZGqtxyRi1w8pmdL6tXj56y0KrkbbLL8nA2QhZ1bBYqm6oiJCP01nffn1ScNTKCHi79vYJ0bsbfVjpV90X+mP5AL8MNiI3aoP251gYDd/I2uAKwk75zruUc+ChERkGqsXXGOb7LrDHVG82hRNs4nQ1HKo9KkBJgh3FdD5YMdl8fA4LmCNqC3EqKIJZOiwmzcn+LZAOqlM+VfcYQWb3VrQmZCjFTlRvH3FaUl1ENZJK0baFr5yZ0/eKjPJ5u3YJ3Xe+OZxmsDrylYxso4IlYeKcd+vbbQVcx100F4Ut8T1g2vCUzkNu9m1ZiaBtm2fAmuK0+SVOD9b3PK8BdvYWm/L70ZyhUA4PJTI5LnAkS4JrnPfeZiCfyVBRp1NTzY91jYuDTtdj0JqQXw5VnaW1r0C0vpwTZfIuIuAl1pCDkEJvCR7YgJx9bWj9+0imab8nnaqz3hj2vGf1XGwzmJqCPrEmGW+lEfSxOEezjLUF5I+cvAdsFgm0bcPnynHkbVAR62md86xJAV6tZghwHlpHSqoW++/OwjiZBsLv2AWnzhHUAIGjNDemyf3UERmyRs2O2N2JwldxcCNiIMxwzw021N716/o+FBu2LkzsSAPUq2QdpH/RlMa0aWuEd9vLKMllM7CJiMSaIWUKqG56MUQ+FMu7fgtlAzymgGqjy0="
        file_glob: true
        file:
        - "release/MeshbluConnectorInstaller*"
        skip_cleanup: true
        # on:
        #   tags: true
    - os: linux
      language: node_js
      node_js: '6'
      dist: trusty
      sudo: false
      cache:
        yarn: true
        directories:
        - $HOME/.electron
        - $HOME/.cache
      addons:
        apt:
          packages:
          - g++-multilib
          - xz-utils
      before_install:
      - npm install --global yarn
      install:
      - yarn install
      - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
      before_script:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start &
      - sleep 3
      script:
      - yarn run test
      - yarn run build
      - yarn run test-e2e
      after_success:
      - yarn run package-linux-all -- --publish onTagOrDraft --draft
      deploy:
      - provider: npm
        email: serveradmin@octoblu.com
        api_key:
          secure: sgFLuz8Or6bk4fD1y0Lr2tkWE4E20YXrTBqDYrHvcpWFiUmgE4q5UckWYHk5v+EYO6Tf0xrGwU863P9mv7wJiaCuK6p0g7JWkvGidnve1stt9X532Xcudmw+VM/kmGxGw4lkmLTgmAU73P+EjoyGMr8hpFgPw3FBF2jy/JPDHXlBimOBxJvHSkzdByj7jPqSBW7nnYIL81CWkq2wKJUXcxU6FPulpelCosoJ7WfzqabqYYZfidQhSl9hlw52F/uEztkv5XrXmUt28swXOhUSQwhmyivtQCuRAe97eok6dHA7vgUzvx7+1erEcTAhX9qysCBPJ4Y5y9+jUVhXrASP6ng60fFPTXZTOdOQpq4XLgRdE0LCQQ5JmVTzkhKLU6SFPfLAFZN7nlBwfH4R8SAXJ9cNLk1ag3YtLk0x6SZFli2u7xi4DCsX/cD/gkpDMDO3jEmyK1OZmNb5wNyXp8c8if9PxxCs2hMXtmptJgJL8i5ZaeTAkUfI/NCV69QWd50NkqhOhwPLlbeJthR4CshODIabRy+D8XuOwDwnJATZSKya8yMBJ2ZCGA0zwxV6TLUBkmlVxcGSLXvhrPs2ODlgfXY+kzL2oZE0An7kk7IZumO5anvoBuvDknnq8NNrQKcvFIwUVTQyf1+NJZsCmTVin5vMuTAWiKZI6TME0Zo34ng=
        on:
          tags: true
# branches:
#   only:
#   - "/^v[0-9]/"
# deploy:
# - provider: npm
#   email: serveradmin@octoblu.com
#   api_key:
#     secure: sgFLuz8Or6bk4fD1y0Lr2tkWE4E20YXrTBqDYrHvcpWFiUmgE4q5UckWYHk5v+EYO6Tf0xrGwU863P9mv7wJiaCuK6p0g7JWkvGidnve1stt9X532Xcudmw+VM/kmGxGw4lkmLTgmAU73P+EjoyGMr8hpFgPw3FBF2jy/JPDHXlBimOBxJvHSkzdByj7jPqSBW7nnYIL81CWkq2wKJUXcxU6FPulpelCosoJ7WfzqabqYYZfidQhSl9hlw52F/uEztkv5XrXmUt28swXOhUSQwhmyivtQCuRAe97eok6dHA7vgUzvx7+1erEcTAhX9qysCBPJ4Y5y9+jUVhXrASP6ng60fFPTXZTOdOQpq4XLgRdE0LCQQ5JmVTzkhKLU6SFPfLAFZN7nlBwfH4R8SAXJ9cNLk1ag3YtLk0x6SZFli2u7xi4DCsX/cD/gkpDMDO3jEmyK1OZmNb5wNyXp8c8if9PxxCs2hMXtmptJgJL8i5ZaeTAkUfI/NCV69QWd50NkqhOhwPLlbeJthR4CshODIabRy+D8XuOwDwnJATZSKya8yMBJ2ZCGA0zwxV6TLUBkmlVxcGSLXvhrPs2ODlgfXY+kzL2oZE0An7kk7IZumO5anvoBuvDknnq8NNrQKcvFIwUVTQyf1+NJZsCmTVin5vMuTAWiKZI6TME0Zo34ng=
#   on:
#     tags: true
