os: unstable
environment:
  nodejs_version: 6
  BUILD_OS: "windows"
  TAG: "%APPVEYOR_REPO_TAG_NAME%"
cache:
- node_modules -> package.json
- app/node_modules -> app/package.json
matrix:
  fast_finish: true
platform:
- x64
- x86
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
skip_non_tags: true
install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - npm install -g npm@latest
  - node -e "console.log(process.arch);"
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
test_script:
- node --version
- npm run lint
- npm run test
- npm run build
- npm run test-e2e
- npm run package
build_script:
  - yarn package
  - ps: . .\deploy\build.ps1
after_build:
  - ps: $root = Resolve-Path dpl_github; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName ConnectorInstaller }
deploy:
- provider: GitHub
  description: 'Meshblu Connector Installer'
  auth_token:
    secure: p0bduMOKSsFF3iSAsZbDLwn5eSgZEUOqx9HEL62vNJwZEOEah3c1WcRN++A8QEYi
  artifact: ConnectorInstaller
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
