os: unstable
environment:
  nodejs_version: 6
  BUILD_OS: "windows"
  TAG: "%APPVEYOR_REPO_TAG_NAME%"
cache:
- node_modules -> package.json
- app/node_modules -> app/package.json
matrix:
  fast_finish: true
platform:
- x64
- x86
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
skip_commits:
  message: /.*/
skip_non_tags: true
install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - npm install -g npm@latest
  - choco install -i yarn
  - refreshenv
  - node -e "console.log(process.arch);"
  - set PATH=%APPDATA%\npm;%PATH%
  - yarn install  
test_script:
- node --version
- yarn run test
- yarn run build
build_script:
  - if "%PLATFORM%" == "x64" yarn run package-win-x64 -- --publish onTag
  - if "%PLATFORM%" == "x86" yarn run package-win-ia32 -- --publish onTag
after_build:
  - ps: $root = Resolve-Path dpl_github; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName ConnectorInstaller }
# deploy:
# - provider: GitHub
#   description: 'Meshblu Connector Installer'
#   auth_token:
#     secure: p0bduMOKSsFF3iSAsZbDLwn5eSgZEUOqx9HEL62vNJwZEOEah3c1WcRN++A8QEYi
#   artifact: ConnectorInstaller
#   draft: false
#   prerelease: false
#   on:
#     branch: master
#     appveyor_repo_tag: true
