#!/bin/bash

print_usage(){
  echo "Usage: build-connector-installer <platform> <arch> <download-dir>"
}

download_installer(){
  local key="$1"
  local platform="$2"
  local arch="$3"
  local output_dir="$4"
  local ext="zip"
  if [ "$platform" == "darwin" ]; then
    ext="dmg"
  fi
  local base_url="https://github.com/octoblu/electron-meshblu-connector-installer"
  local download_url="${base_url}/releases/download/v4.0.0/MeshbluConnectorInstaller-${platform}-${arch}.${ext}"
  local output_file="$output_dir/MeshbluConnectorInstaller-${key}.${ext}"
  echo "* downloading... $download_url"
  echo "* to $output_file"
  curl -L "$download_url" -o "$output_file"
  if [ ! -f "$output_file" ]; then
    echo "Invalid downloaded file"
    exit 1
  fi
}

main(){
  if [ "$1" == "--help" -o "$1" == "-h" -o "$1" == "help" -o "$1" == "-?" ]; then
    print_usage
    exit 1
  fi
  local platform="$2"
  local arch="$3"
  local output_dir="$4"

  if [ -z "$platform" ]; then
    print_usage
    echo "Missing platform"
    exit 1
  fi

  if [ -z "$arch" ]; then
    print_usage
    echo "Missing arch"
    exit 1
  fi

  if [ -z "$output_dir" -a -d "$output_dir" ]; then
    print_usage
    echo "Missing or invalid output_dir"
    exit 1
  fi

  echo "* generating key"
  local key="$(./scripts/create-test-key)"
  echo "* key: $key"

  echo "* download app"
  download_installer "$key" "$platform" "$arch" "$output_dir"

  echo "* done"
}

main "$@"
